import { APP, STORES, DEFAULTS, CATEGORIES } from './config.js';
import * as db from './db.js';
import { sum,round,availableCash,safeToSpend,cashFlow,sinkingContribution,futureValue,debtAvalanche,affordability,phase,savingsRate } from './finance.js';

const $=s=>document.querySelector(s), content=$('#content'), modal=$('#modal'), modalContent=$('#modal-content');
let state={}, currentView='dashboard', waitingWorker=null;
const money=n=>new Intl.NumberFormat(APP.locale,{style:'currency',currency:APP.currency,maximumFractionDigits:0}).format(Number(n)||0).replace('KES','KSh').replace('Ksh','KSh');
const dateFmt=d=>new Intl.DateTimeFormat(APP.locale,{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${d}T12:00:00`));
const id=()=>crypto.randomUUID(); const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const nowDate=()=>new Date().toISOString().slice(0,10); const daysLeft=()=>{const n=new Date(),end=new Date(n.getFullYear(),n.getMonth()+1,0);return Math.max(1,end.getDate()-n.getDate()+1)};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function load(){for(const s of STORES)state[s]=await db.getAll(s);state.settings=(state.settings||[]).find(x=>x.id==='profile')||structuredClone(DEFAULTS.settings);applyPrefs();}
function applyPrefs(){document.documentElement.dataset.theme=state.settings?.theme==='system'?'':state.settings?.theme||'';document.body.classList.toggle('balance-hidden',!!state.settings?.hideBalances);$('#hide-btn').textContent=state.settings?.hideBalances?'◎':'◉'}
const txThisMonth=()=>{const ym=new Date().toISOString().slice(0,7);return state.transactions.filter(t=>t.date.startsWith(ym));};
function metrics(){const accounts=state.accounts.filter(a=>a.type==='cash'),txs=txThisMonth(),out=txs.filter(t=>t.type==='expense'),income=txs.filter(t=>t.type==='income'),budget=sum(state.budgets),spent=sum(out),avail=availableCash(accounts),debt=sum(state.loans,'balance'),minimums=sum(state.loans.filter(l=>l.balance>0),'minPayment'),plannedRemaining=Math.max(0,budget-spent),safe=safeToSpend({available:avail,plannedRemaining,debtRemaining:Math.max(0,state.settings.debtBudget-minimums),daysRemaining:daysLeft()}),emergency=sum(state.emergencyFunds,'balance'),investments=sum(state.investments,'balance')+sum(state.accounts.filter(a=>a.type==='investment'),'balance');return{accounts,txs,out,income,budget,spent,avail,debt,minimums,plannedRemaining,safe,emergency,investments,netWorth:sum(state.accounts,'balance')+sum(state.investments,'balance')+emergency-debt,phase:phase({debt,emergency,target:state.settings.emergencyTarget})};}
function progress(value,max){return `<div class="progress"><i style="width:${Math.min(100,max?value/max*100:0)}%"></i></div>`}
function empty(text){return `<div class="empty">${text}</div>`}
function renderDashboard(){const m=metrics(),av=debtAvalanche(state.loans,state.settings.debtBudget),rec=state.recommendations.find(r=>r.status==='active'),originalDebt=sum(state.loans,'original'),essentialMonthly=sum(state.budgets.filter(b=>b.kind==='essential')),wealthRate=savingsRate(state.settings.wealthTarget,state.settings.salary),quick=name=>round((state.budgets.find(b=>b.name===name)?.amount||0)/Math.max(1,state.settings.workdays));return `<section class="hero"><div><span class="label muted">Actually free after commitments</span><div class="metric-value money">${money(m.avail)}</div><p class="muted">Your cash balance is ${money(sum(m.accounts,'balance'))}; ${money(sum(m.accounts,'committed'))} is already spoken for.</p><div class="metric-row"><div class="hero-stat"><strong class="money">${money(m.safe.daily)}</strong><small>Safe per day</small></div><div class="hero-stat"><strong class="money">${money(m.debt)}</strong><small>Debt remaining</small></div><div class="hero-stat"><strong class="money">${money(m.netWorth)}</strong><small>Net worth</small></div></div></div><div class="phase-card"><span class="label muted">Current financial phase</span><h3>${m.phase}</h3><p class="muted">${m.phase==='Debt elimination'?`Keep minimums current and direct ${money(av.extra)} extra to ${esc(av.target?.name||'the highest-rate loan')}.`:m.phase==='Emergency fund'?'Build accessible reserves before maximizing long-term investing.':`Protect your ${wealthRate}% wealth-building target.`}</p>${progress(m.phase==='Debt elimination'?Math.max(0,originalDebt-m.debt):m.emergency,m.phase==='Debt elimination'?originalDebt:state.settings.emergencyTarget)}</div></section>
<div class="grid">${rec?`<article class="card wide callout"><span class="label">Suggested next move</span><h2>Use the expected ${money(rec.incoming)} deliberately</h2><p>After it arrives, consider confirming the priority lender’s full settlement figure, using about <strong>${money(rec.debtAmount)}</strong> toward settlement, then directing about <strong>${money(rec.modifiedAmount??rec.investmentAmount)}</strong> to long-term investment.</p><p class="muted">Conditional on the recorded figure being the current full early-settlement amount with no punitive penalty. Nothing is recorded automatically.</p><div class="actions"><button class="primary" data-rec="complete">Mark completed</button><button class="secondary" data-action="edit-recommendation">Modify</button><button class="text-btn" data-rec="dismissed">Dismiss</button></div></article>`:''}<article class="card"><span class="label">Monthly plan</span><div class="amount money">${money(m.spent)} / ${money(m.budget)}</div>${progress(m.spent,m.budget)}<p class="muted">${money(m.plannedRemaining)} remains across budget categories.</p></article><article class="card"><span class="label">Debt target</span><div class="amount money">${money(state.settings.debtBudget)}</div><p class="muted">Minimums total ${money(m.minimums)}. Extra capacity: ${money(Math.max(0,state.settings.debtBudget-m.minimums))}.</p></article><article class="card"><span class="label">Emergency reserve</span><div class="amount money">${money(m.emergency)}</div>${progress(m.emergency,state.settings.emergencyTarget)}<p class="muted">Target ${money(state.settings.emergencyTarget)} · ${m.emergency&&essentialMonthly? (m.emergency/essentialMonthly).toFixed(1):'0'} essential months.</p></article><article class="card wide"><h2>Recent activity</h2>${renderTxList(state.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5))}</article><article class="card"><h2>Quick workday</h2><p class="muted">Uses monthly workday budgets divided by your configured workdays.</p><div class="actions"><button class="secondary" data-quick="Transport" data-amount="${quick('Transport')}">Transport ${money(quick('Transport'))}</button><button class="secondary" data-quick="Lunch" data-amount="${quick('Lunch')}">Lunch ${money(quick('Lunch'))}</button><button class="secondary" data-quick="Breakfast" data-amount="${quick('Breakfast')}">Breakfast ${money(quick('Breakfast'))}</button></div></article></div>`}
function renderTxList(rows){return rows.length?`<div class="list">${rows.map(t=>`<div class="list-row"><div><strong>${esc(t.description||t.category)}</strong><p class="muted">${dateFmt(t.date)} · ${esc(t.category)} · ${t.planned?'Planned':'Unplanned'}</p></div><strong class="money" style="color:${t.type==='income'?'var(--good)':'inherit'}">${cashFlow(t)>0?'+':''}${money(cashFlow(t))}</strong></div>`).join('')}</div>`:empty('No transactions yet. Add one when money moves.')}
function renderMoney(){const m=metrics();return `<div class="grid"><article class="card wide"><h2>Accounts</h2>${state.accounts.map(a=>`<div class="list-row"><div><strong>${esc(a.name)}</strong><p class="muted">${esc(a.type)} · ${money(a.committed||0)} committed</p></div><strong class="money">${money(a.balance)}</strong></div>`).join('')}<div class="actions"><button class="secondary" data-action="add-account">Add account</button></div></article><article class="card"><h2>Cash clarity</h2><span class="label">Total cash</span><div class="amount money">${money(sum(m.accounts,'balance'))}</div><p>Committed <strong class="money">${money(sum(m.accounts,'committed'))}</strong></p><p>Available <strong class="money">${money(m.avail)}</strong></p></article><article class="card full"><div style="display:flex;justify-content:space-between;gap:15px"><h2>Transactions</h2><button class="primary" data-action="add-transaction">Add transaction</button></div>${renderTxList(state.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)))}</article></div>`}
function renderBudget(){const m=metrics(),spendBy=Object.fromEntries(state.budgets.map(b=>[b.name,sum(m.out.filter(t=>t.category===b.name))]));return `<div class="grid"><article class="card"><span class="label">Safe to spend</span><div class="amount money">${money(m.safe.total)}</div><p class="muted">${money(m.safe.daily)} per remaining day after budget and debt protection.</p></article><article class="card"><span class="label">Planned vs unplanned</span><div class="amount money">${money(sum(m.out.filter(t=>!t.planned)))}</div><p class="muted">Unplanned this month · ${money(sum(m.out.filter(t=>t.planned)))} planned.</p></article><article class="card"><h2>Can I afford this?</h2><div class="field"><label>Purchase amount</label><input id="afford-cost" type="number" min="0" placeholder="e.g. 15000"></div><div class="actions"><button class="secondary" data-action="check-afford">Check safely</button></div><div id="afford-result"></div></article><article class="card full"><h2>Monthly budget</h2><table><thead><tr><th>Category</th><th>Plan</th><th>Spent</th><th>Status</th></tr></thead><tbody>${state.budgets.map(b=>`<tr><td>${esc(b.name)}</td><td class="money">${money(b.amount)}</td><td class="money">${money(spendBy[b.name]||0)}</td><td>${spendBy[b.name]>b.amount?'<span class="tag warn">Over</span>':'<span class="tag good">On track</span>'}</td></tr>`).join('')}</tbody></table><div class="actions"><button class="secondary" data-action="add-budget">Add category</button></div></article><article class="card wide"><h2>Recurring commitments</h2>${state.recurringCommitments.map(c=>`<div class="list-row"><div><strong>${esc(c.name)}</strong><p class="muted">Due day ${c.dueDay} · ${esc(c.category)}</p></div><strong class="money">${money(c.amount)}</strong></div>`).join('')}</article><article class="card"><h2>Alerts</h2>${m.spent>m.budget?'<p class="tag warn">Monthly spending exceeds plan</p>':'<p class="tag good">Spending is within plan</p>'}${sum(m.out.filter(t=>!t.planned))>m.budget*.15?'<p class="tag warn">Unplanned spending is above 15%</p>':'<p class="muted">No unusual deterministic alert.</p>'}</article></div>`}
function renderGoals(){const m=metrics(),av=debtAvalanche(state.loans,state.settings.debtBudget),wealthRate=savingsRate(state.settings.wealthTarget,state.settings.salary);return `<div class="grid"><article class="card full"><h2>Debt avalanche</h2><p class="muted">Pay all minimums, then direct ${money(av.extra)} extra to the highest annual rate. Loans are purposeful obligations—not a moral score.</p>${av.order.map((l,i)=>`<div class="list-row"><div><span class="tag ${i===0?'warn':''}">${i===0?'Attack now':`Priority ${i+1}`}</span> <strong>${esc(l.name)}</strong><p class="muted">${l.rate}% p.a. · minimum ${money(l.minPayment)} · ${esc(l.purpose)}</p>${progress(l.original-l.balance,l.original)}</div><strong class="money">${money(l.balance)}</strong></div>`).join('')}<div class="actions"><button class="secondary" data-action="add-loan-payment">Record payment</button></div></article><article class="card"><h2>Emergency fund</h2><div class="amount money">${money(m.emergency)}</div>${progress(m.emergency,state.settings.emergencyTarget)}<p class="muted">Keep a same-day-access layer and a separated, liquid, low-risk reserve.</p><button class="secondary" data-action="add-emergency">Add balance</button></article><article class="card"><h2>Sinking funds</h2>${state.sinkingFunds.length?state.sinkingFunds.map(f=>`<div class="list-row"><div><strong>${esc(f.name)}</strong><p class="muted">Suggested ${money(sinkingContribution(f.target,f.balance,f.targetDate))}/month</p></div><span class="money">${money(f.balance)} / ${money(f.target)}</span></div>`).join(''):empty('Separate predictable irregular costs from emergencies.')}<button class="secondary" data-action="add-sinking">Create fund</button></article><article class="card"><h2>Investments</h2><div class="amount money">${money(m.investments)}</div><p class="muted">Long-term capital, separate from operating cash and emergency reserves.</p><button class="secondary" data-action="projection">Project future value</button></article><article class="card"><h2>Net worth</h2><div class="amount money">${money(m.netWorth)}</div><p class="muted">Tracked assets less current loan balances. Add property manually when you have a defensible value.</p></article><article class="card"><h2>Wealth phase rule</h2><div class="amount">${wealthRate}%</div><p class="muted">After debt and emergency funding: ${money(state.settings.wealthTarget)} wealth, ${money(state.settings.livingTarget)} current life.</p><small>Current tracked investment rate: ${savingsRate(m.investments,state.settings.salary)}%</small></article></div>`}
function renderReviews(){return `<div class="grid"><article class="card"><h2>Daily close</h2><p class="muted">Confirm today’s transactions, planned status, and account balance.</p><button class="primary" data-close="dailyCloses">Close today</button><p>${state.dailyCloses.length} recorded</p></article><article class="card"><h2>Weekly review</h2><p class="muted">Review unplanned spending, commitments, debt progress, and next week’s known costs.</p><button class="secondary" data-action="weekly-review">Start review</button></article><article class="card"><h2>Monthly close</h2><p class="muted">Freeze a summary snapshot without locking future corrections.</p><button class="primary" data-close="monthlyCloses">Close month</button><p>${state.monthlyCloses.length} recorded</p></article><article class="card wide"><h2>Payday runbook</h2><ol><li>Confirm salary received and account balances.</li><li>Reserve rent, utilities, food, transport and known commitments.</li><li>Pay every loan minimum.</li><li>Direct remaining debt budget to the avalanche target.</li><li>Fund emergencies/sinking funds appropriate to the current phase.</li><li>Invest only capital not needed for operating cash.</li></ol><button class="secondary" data-action="payday">Run payday checklist</button></article><article class="card"><h2>Reminder definitions</h2>${state.reminders.map(r=>`<p><strong>${esc(r.name)}</strong><br><span class="muted">${esc(r.schedule)}</span></p>`).join('')}<button class="secondary" data-action="ics">Export calendar (.ics)</button><p class="muted">Browsers cannot guarantee background alarms. Calendar export is the reliable cross-device option.</p></article></div>`}
function renderSettings(){const s=state.settings;return `<div class="grid"><article class="card wide"><h2>Editable plan</h2><form id="settings-form" class="form-grid"><div class="field"><label>Monthly net salary</label><input name="salary" type="number" value="${s.salary}"></div><div class="field"><label>Debt elimination target</label><input name="debtBudget" type="number" value="${s.debtBudget}"></div><div class="field"><label>Living target</label><input name="livingTarget" type="number" value="${s.livingTarget}"></div><div class="field"><label>Wealth target</label><input name="wealthTarget" type="number" value="${s.wealthTarget}"></div><div class="field"><label>Emergency target</label><input name="emergencyTarget" type="number" value="${s.emergencyTarget}"></div><div class="field"><label>Average workdays/month</label><input name="workdays" type="number" step=".1" value="${s.workdays}"></div><div class="actions field full"><button class="primary" type="submit">Save settings</button></div></form></article><article class="card"><h2>Appearance</h2><div class="field"><label>Theme</label><select id="theme-select"><option value="system" ${s.theme==='system'?'selected':''}>System</option><option value="light" ${s.theme==='light'?'selected':''}>Light</option><option value="dark" ${s.theme==='dark'?'selected':''}>Dark</option></select></div><label><input id="privacy-toggle" type="checkbox" ${s.hideBalances?'checked':''}> Hide financial balances</label></article><article class="card"><h2>Backup & portability</h2><p class="muted">Data does not sync between phone and laptop. Export a backup regularly.</p><div class="actions"><button class="secondary" data-action="backup">Export JSON</button><button class="secondary" data-action="restore">Restore JSON</button><button class="secondary" data-action="csv">Transactions CSV</button></div></article><article class="card full callout"><h2>Privacy</h2><p>Your financial data is stored locally on this device/browser. SaveCoin does not transmit your financial records to a server.</p><p class="muted">Clearing site data or losing the device can erase records. The balance-hiding control protects against casual glances; it is not encryption.</p></article></div>`}
const renderers={dashboard:renderDashboard,money:renderMoney,budget:renderBudget,goals:renderGoals,reviews:renderReviews,settings:renderSettings};
function render(view=currentView){currentView=view;content.innerHTML=renderers[view]();$('#view-title').textContent={dashboard:'Overview',money:'Money',budget:'Monthly plan',goals:'Goals & wealth',reviews:'Close & review',settings:'Settings'}[view];document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));location.hash=view==='dashboard'?'':view;}
function showForm(title,body,onSubmit){modalContent.innerHTML=`<h2>${title}</h2><div class="form-grid">${body}</div><div class="actions"><button class="primary" value="default" id="modal-save">Save</button><button class="secondary" value="cancel">Cancel</button></div>`;modal.showModal();$('#modal-save').onclick=e=>{e.preventDefault();onSubmit(new FormData(modal.querySelector('form')))};}
function showOnboarding(){
  const setupField=(name,label,required=true)=>`<div class="field"><label>${label}</label><input name="${name}" type="number" min="0" step="0.01" ${required?'required':''}></div>`;
  modalContent.innerHTML=`<span class="tag good">Private · local-first</span><h2>Set up your private money plan</h2><p>Enter your current figures. They are saved only in this browser and are never transmitted by SaveCoin.</p><div id="onboarding-form"><h3>Income, cash and targets</h3><div class="form-grid">${setupField('salary','Monthly net salary')}${setupField('cashBalance','Operating cash balance')}${setupField('committedCash','Cash already committed')}${setupField('debtBudget','Monthly debt-elimination target')}${setupField('livingTarget','Monthly living target')}${setupField('wealthTarget','Monthly wealth target')}${setupField('emergencyTarget','Emergency-fund target')}${setupField('investmentReturn','Expected investment return (%)',false)}${setupField('expectedReceipt','Expected incoming repayment',false)}</div><h3>Current loans</h3><div class="form-grid">${setupField('loan1Balance','Loan 1 balance',false)}${setupField('loan1Rate','Loan 1 annual rate (%)',false)}${setupField('loan1Minimum','Loan 1 monthly minimum',false)}${setupField('loan2Balance','Loan 2 balance',false)}${setupField('loan2Rate','Loan 2 annual rate (%)',false)}${setupField('loan2Minimum','Loan 2 monthly minimum',false)}${setupField('priorityBalance','Priority-loan settlement balance',false)}${setupField('priorityRate','Priority-loan annual rate (%)',false)}${setupField('priorityMinimum','Priority-loan monthly minimum',false)}</div><h3>Known monthly essentials</h3><div class="form-grid">${setupField('rent','Rent',false)}${setupField('water','Water',false)}${setupField('electricity','Electricity',false)}${setupField('wifi','Wi-Fi',false)}${setupField('transport','Transport',false)}${setupField('lunch','Lunch',false)}${setupField('breakfast','Breakfast',false)}${setupField('chatgpt','Subscriptions / ChatGPT',false)}</div><p class="muted">Optional fields may be left blank and completed later. You can edit all targets in Settings.</p><div class="actions"><button class="primary" id="onboarding-save" type="button">Save private plan</button></div></div>`;
  modal.showModal();
  $('#onboarding-save').onclick=async e=>{e.preventDefault();const required=[...modal.querySelectorAll('#onboarding-form input[required]')];if(required.some(input=>!input.value)){required.find(input=>!input.value).focus();toast('Complete the required setup fields');return}const f=new FormData(modal.querySelector('form')),num=name=>Number(f.get(name))||0;
    Object.assign(state.settings,{salary:num('salary'),debtBudget:num('debtBudget'),livingTarget:num('livingTarget'),wealthTarget:num('wealthTarget'),emergencyTarget:num('emergencyTarget'),setupComplete:true});await db.put('settings',state.settings);
    const cash=state.accounts.find(a=>a.id==='operating-cash'),investment=state.accounts.find(a=>a.id==='long-term-investment');Object.assign(cash,{balance:num('cashBalance'),committed:num('committedCash')});investment.expectedReturn=num('investmentReturn');await db.put('accounts',cash);await db.put('accounts',investment);
    const loanValues=[['loan-1','loan1Balance','loan1Rate','loan1Minimum'],['loan-2','loan2Balance','loan2Rate','loan2Minimum'],['priority-loan','priorityBalance','priorityRate','priorityMinimum']];for(const [loanId,balance,rate,minimum] of loanValues){const loan=state.loans.find(l=>l.id===loanId);Object.assign(loan,{balance:num(balance),original:num(balance),rate:num(rate),minPayment:num(minimum)});await db.put('loans',loan)}
    const budgetFields=['rent','water','electricity','wifi','transport','lunch','breakfast','chatgpt'];for(const key of budgetFields){const row=state.budgets.find(b=>b.id===key);row.amount=num(key);await db.put('budgets',row);const recurring=state.recurringCommitments.find(c=>c.id===key);if(recurring){recurring.amount=num(key);await db.put('recurringCommitments',recurring)}}const known=sum(state.budgets.filter(b=>b.id!=='flexible'));const flexible=state.budgets.find(b=>b.id==='flexible');flexible.amount=Math.max(0,state.settings.livingTarget-known);await db.put('budgets',flexible);
    const incoming=num('expectedReceipt'),priority=num('priorityBalance');if(incoming>0){await db.put('recommendations',{id:'expected-receipt',status:'active',incoming,debtAmount:Math.min(incoming,priority),investmentAmount:Math.max(0,incoming-priority),modifiedAmount:null})}
    modal.close();await refresh();toast('Your private plan is ready')};
}
const field=(name,label,type='text',value='',extra='')=>`<div class="field"><label>${label}</label><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`;
const categoryOptions=selected=>Object.entries(CATEGORIES).map(([group,items])=>`<optgroup label="${esc(group)}">${items.map(item=>`<option value="${esc(item)}" ${item===selected?'selected':''}>${esc(item)}</option>`).join('')}</optgroup>`).join('');
async function addTransaction(preset={}){showForm('Add transaction',`${field('date','Date','date',nowDate(),'required')}${field('amount','Amount (KSh)','number',preset.amount||'','min="0" required')}<div class="field"><label>Type</label><select name="type"><option value="expense">Expense</option><option value="income">Income</option><option value="transfer">Transfer</option></select></div><div class="field"><label>Category</label><select name="category" required><option value="" ${preset.category?'':'selected'} disabled>Choose a category</option>${categoryOptions(preset.category)}</select></div>${field('description','Description','text',preset.category||'')}<div class="field"><label>Account</label><select name="accountId">${state.accounts.map(a=>`<option value="${a.id}" ${a.type==='cash'?'selected':''}>${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label>Transfer destination (optional)</label><select name="toAccountId"><option value="">Not a transfer</option>${state.accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label><input name="planned" type="checkbox" checked> Planned</label></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div>`,async f=>{const row={id:id(),date:f.get('date'),amount:Number(f.get('amount')),type:f.get('type'),category:f.get('category'),description:f.get('description'),accountId:f.get('accountId'),toAccountId:f.get('toAccountId')||null,planned:f.get('planned')==='on',notes:f.get('notes'),createdAt:new Date().toISOString()};if(row.type==='transfer'&&(!row.toAccountId||row.toAccountId===row.accountId)){alert('Choose a different destination account for a transfer.');return}await db.put('transactions',row);const a=state.accounts.find(x=>x.id===row.accountId);if(a){if(row.type==='transfer'){const to=state.accounts.find(x=>x.id===row.toAccountId);a.balance-=row.amount;to.balance+=row.amount;await db.put('accounts',to)}else a.balance+=cashFlow(row);await db.put('accounts',a)}modal.close();await refresh();toast('Transaction recorded')})}
async function refresh(){await load();render(currentView)}
async function handleAction(a){
  if(a==='add-transaction')return addTransaction();
  if(a==='add-account')return showForm('Add account',field('name','Name')+field('balance','Opening balance','number',0)+`<div class="field"><label>Type</label><select name="type"><option value="cash">Cash / wallet</option><option value="investment">Investment</option><option value="asset">Asset</option></select></div>`+field('committed','Committed amount','number',0),async f=>{await db.put('accounts',{id:id(),name:f.get('name'),balance:Number(f.get('balance')),committed:Number(f.get('committed')),type:f.get('type')});modal.close();await refresh()});
  if(a==='add-budget')return showForm('Add budget category',field('name','Category')+field('amount','Monthly plan','number'),async f=>{await db.put('budgets',{id:id(),name:f.get('name'),amount:Number(f.get('amount')),kind:'flexible'});modal.close();await refresh()});
  if(a==='check-afford'){const m=metrics(),cost=Number($('#afford-cost').value),r=affordability({cost,available:m.avail,safe:m.safe.total});$('#afford-result').innerHTML=`<p class="tag ${r.affordable?'good':'warn'}">${r.message}</p><p class="muted">Safe room: ${money(r.room)}${r.shortfall?` · short by ${money(r.shortfall)}`:''}</p>`;return}
  if(a==='add-loan-payment')return showForm('Record loan payment',`<div class="field"><label>Loan</label><select name="loanId">${state.loans.filter(l=>l.balance>0).map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')}</select></div>`+field('amount','Principal reduction','number')+field('date','Date','date',nowDate()),async f=>{const loan=state.loans.find(l=>l.id===f.get('loanId')),amount=Number(f.get('amount'));loan.balance=Math.max(0,loan.balance-amount);await db.put('loans',loan);await db.put('loanPayments',{id:id(),loanId:loan.id,amount,date:f.get('date')});modal.close();await refresh()});
  if(a==='add-emergency')return showForm('Update emergency reserve',field('name','Account name','text','Emergency Cash')+field('balance','Current balance','number',0),async f=>{await db.put('emergencyFunds',{id:id(),name:f.get('name'),balance:Number(f.get('balance'))});modal.close();await refresh()});
  if(a==='add-sinking')return showForm('Create sinking fund',field('name','Name')+field('target','Target amount','number')+field('balance','Current balance','number',0)+field('targetDate','Target date','date'),async f=>{await db.put('sinkingFunds',{id:id(),name:f.get('name'),target:Number(f.get('target')),balance:Number(f.get('balance')),targetDate:f.get('targetDate')});modal.close();await refresh()});
  if(a==='projection'){const investment=state.accounts.find(x=>x.type==='investment');return showForm('Investment projection',field('balance','Current balance','number',metrics().investments)+field('monthly','Monthly contribution','number',state.settings.wealthTarget)+field('rate','Expected annual return (%)','number',investment?.expectedReturn||0)+field('years','Years','number',10),f=>{const v=futureValue(+f.get('balance'),+f.get('monthly'),+f.get('rate'),+f.get('years'));modalContent.innerHTML=`<h2>Estimated future value</h2><div class="metric-value money">${money(v)}</div><p>Assumes monthly compounding and a steady ${f.get('rate')}% annual return. This is an estimate, not a guarantee; rates and returns can change.</p><button class="primary" value="cancel">Done</button>`})}
  if(a==='edit-recommendation'){const current=state.recommendations.find(x=>x.status==='active');return showForm('Modify suggested split',field('investmentAmount','Amount to invest','number',current?.investmentAmount||0),async f=>{current.modifiedAmount=Number(f.get('investmentAmount'));await db.put('recommendations',current);modal.close();await refresh()})}
  if(a==='backup'){const data=await db.exportAll();return download(`savecoin-backup-${nowDate()}.json`,JSON.stringify(data,null,2),'application/json')}
  if(a==='restore'){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const data=JSON.parse(await input.files[0].text());if(!db.validateBackup(data))throw Error('Backup format is not supported');const counts=Object.entries(data.stores).map(([k,v])=>`${k}: ${v.length}`).join('\n');if(confirm(`Restore this backup? Existing local data will be replaced.\n\n${counts}`)){await db.restoreAll(data);await refresh();toast('Backup restored')}}catch(e){alert(e.message)}};return input.click()}
  if(a==='csv'){const cols=['date','amount','category','accountId','type','planned','description','notes'],q=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv=[cols.join(','),...state.transactions.map(t=>cols.map(c=>q(t[c])).join(','))].join('\r\n');return download(`savecoin-transactions-${nowDate()}.csv`,csv,'text/csv')}
  if(a==='ics'){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//SaveCoin//Personal Finance//EN',...state.reminders.flatMap((r,i)=>['BEGIN:VEVENT',`UID:${r.id}@savecoin`,`DTSTART:2026090${Math.min(i+1,9)}T180000`,`RRULE:FREQ=${r.id==='daily-close'?'DAILY':r.id==='weekly-review'?'WEEKLY':'MONTHLY'}`,`SUMMARY:SaveCoin: ${r.name}`,'DESCRIPTION:Open SaveCoin and complete your local financial review.','END:VEVENT']),'END:VCALENDAR'];return download('savecoin-reminders.ics',lines.join('\r\n'),'text/calendar')}
  if(a==='weekly-review'||a==='payday'){modalContent.innerHTML=`<h2>${a==='payday'?'Payday checklist':'Weekly review'}</h2><p>Use the checklist on the page, verify account balances and transactions, then record any needed adjustments. SaveCoin will never move money automatically.</p><button class="primary" value="cancel">Understood</button>`;return modal.showModal()}
}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.classList.contains('dialog-close')){modal.close();return}if(b.dataset.view)render(b.dataset.view);if(b.dataset.action)await handleAction(b.dataset.action);if(b.dataset.quick)await addTransaction({category:b.dataset.quick,amount:b.dataset.amount});if(b.dataset.rec){const r=state.recommendations.find(x=>x.status==='active');r.status=b.dataset.rec;await db.put('recommendations',r);await refresh()}if(b.dataset.close){const m=metrics(),store=b.dataset.close,key=store==='dailyCloses'?nowDate():nowDate().slice(0,7);await db.put(store,{id:key,closedAt:new Date().toISOString(),spent:m.spent,debt:m.debt,netWorth:m.netWorth,unplanned:sum(m.out.filter(t=>!t.planned))});await refresh();toast(store==='dailyCloses'?'Day closed':'Month closed')}});
document.addEventListener('submit',async e=>{if(e.target.id!=='settings-form')return;e.preventDefault();const f=new FormData(e.target);for(const k of ['salary','debtBudget','livingTarget','wealthTarget','emergencyTarget','workdays'])state.settings[k]=Number(f.get(k));await db.put('settings',state.settings);await refresh();toast('Settings saved')});
document.addEventListener('change',async e=>{if(e.target.id==='theme-select'){state.settings.theme=e.target.value;await db.put('settings',state.settings);applyPrefs()}if(e.target.id==='privacy-toggle'){state.settings.hideBalances=e.target.checked;await db.put('settings',state.settings);applyPrefs()}});
$('#hide-btn').onclick=async()=>{state.settings.hideBalances=!state.settings.hideBalances;await db.put('settings',state.settings);applyPrefs()};
async function initSW(){if(!('serviceWorker'in navigator))return;const reg=await navigator.serviceWorker.register('./sw.js');if(reg.waiting)showUpdate(reg.waiting);reg.addEventListener('updatefound',()=>{const w=reg.installing;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)showUpdate(w)})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}
function showUpdate(w){waitingWorker=w;$('#update-banner').classList.remove('hidden')}$('#update-btn').onclick=()=>waitingWorker?.postMessage({type:'SKIP_WAITING'});
$('#today').textContent=new Intl.DateTimeFormat(APP.locale,{weekday:'long',day:'numeric',month:'long'}).format(new Date());await db.seedIfEmpty();await load();render(location.hash.slice(1) in renderers?location.hash.slice(1):'dashboard');if(!state.settings.setupComplete)showOnboarding();initSW().catch(console.error);
